# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GridClipper
                                 A QGIS plugin
 This plugin clips a raster image using a split grid.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-28
        copyright            : (C) 2021 by Kamand Bagherian
        email                : kzb0086@auburn.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GridClipper class from file GridClipper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .grid_clipper import GridClipper
    return GridClipper(iface)
